services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "8443:443"
    depends_on:
      - wordpress
    networks:
      - inception_net

  mariadb:
    build: ./requirements/mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./run/secrets:/run/secrets
    networks:
      - inception_net

  wordpress:
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    environment:
      SQLDB_USER: user
      SQLDB_NAME: wordpress
      WP_TITLE: "My Site"
      DOMAIN_NAME: "https://localhost:443"
      WP_ADMIN_USER: admin
      WP_ADMIN_EMAIL: admin@example.com
      WP_USER: author
      WP_USER_EMAIL: author@example.com
      WP_USER_PASSWORD: authorpass
    volumes:
      - wp_data:/var/www/html
      - ./run/secrets:/run/secrets
    networks:
      - inception_net

secrets:
  db_root_password:
    file: ../run/secrets/db_root_password
  db_password:
    file: ../run/secrets/db_password
  wp_password:
    file: ../run/secrets/wp_password
  wp_admin_password:
    file: ../run/secrets/wp_admin_password


volumes:
  db_data:
  wp_data:

networks:
  inception_net:




